export const ORDERS_ACTION_TYPES = {
    ADD_TO_ORDERS: 'orders/ADD_TO_ORDERS',
    FETCH_ORDERS_START: 'orders/FETCH_ORDERS_START',
    FETCH_ORDERS_SUCCESS: 'orders/FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAILED: 'orders/FETCH_ORDERS_FAILED',
}