export const ORDER_HISTORY_ACTION_TYPES = {
    FETCH_ORDER_HISTORY_START: 'orderhistory/FETCH_ORDER_HISTORY_START',
    FETCH_ORDER_HISTORY_SUCCESS: 'orderhistory/FETCH_ORDER_HISTORY_SUCCESS',
    FETCH_ORDER_HISTORY_FAILED: 'orderhistory/FETCH_ORDER_HISTORY_FAILED',
}